<definitions name="VoucherService"
   targetNamespace="http://www.examples.com/wsdl/VoucherService.wsdl"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns="http://www.examples.com/wsdl/VoucherService.wsdl"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema">

   <message name="GetLinkVoucherRequest">
      <flight>
          <part name="carrierCode" type="xsd:string"/>
          <part name="flightNumber" type="xsd:string"/>
				  <part name="arrivalStation" type="xsd:string"/>
				  <part name="departureDate" type="xsd:string"/>
				  <part name="departureStation" type="xsd:string"/>
      </flight>

      <passager>
          <part name="upi" type="xsd:string"/>
      </passager>

      <voucher>
          <part name="amount" type="xsd:string"/>
      </voucher>
   </message>

   <message name="GetLinkVoucherResponse">
      <part name="greeting" type="xsd:string"/>
   </message>

   <portType name="Voucher_PortType">
      <operation name="sayVoucher">
         <input message="tns:GetLinkVoucherRequest"/>
         <output message="tns:GetLinkVoucherResponse"/>
      </operation>
   </portType>

   <binding name="Voucher_Binding" type="tns:Voucher_PortType">
      <soap:binding style="rpc"
         transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="sayVoucher">
         <soap:operation soapAction="sayVoucher"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:helloservice"
               use="encoded"/>
         </input>

         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:helloservice"
               use="encoded"/>
         </output>
      </operation>
   </binding>

   <service name="Voucher_Service">
      <documentation>WSDL File for VoucherService</documentation>
      <port binding="tns:Voucher_Binding" name="Voucher_Port">
         <soap:address
            location="http://localhost:3000/voucherservice/" />
      </port>
   </service>
</definitions>
